spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wlcm2church
    username: root
    password: tydb2019
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true